# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'Chatwoot'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.png'
- name: LOGO
  value: '/brand-assets/logo.png'
- name: LOGO_DARK
  value: '/brand-assets/logo_dark.png'
- name: BRAND_URL
  value: 'https://www.mycodek.com'
- name: WIDGET_BRAND_URL
  value: 'https://www.mycodek.com'
- name: BRAND_NAME
  value: 'Chatwoot'
- name: TERMS_URL
  value: 'https://www.mycodek.com/terms-of-service'
- name: PRIVACY_URL
  value: 'https://www.mycodek.com/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
